name: Publish

on: 
  workflow_dispatch

jobs:
  source:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
      - run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          python setup.py sdist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: source
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        name: Set up QEMU
      - run: python -m pip install cibuildwheel
      - run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_ARCHS_LINUX: "auto aarch64 ppc64le"
      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
          if-no-files-found: error
  publish:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/download-artifact@v4.1.7
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          packages_dir: artifact
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
